version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db:/var/lib/mysql
    ports:
    - 3307:3306
  app:
    depends_on:
      - mysqldb
    build:
      context: .
      target: builder
    command: sh -c -f "yarn mikro-orm schema:update --run&&yarn mikro-orm seeder:run --class=ConfigSeeder;yarn run start:prod"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src/:/app/src/
      - static:/app/dist/public/files
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
volumes: 
    db:
    static: